### ISSUE TITLE
'Number of images' count below Folder icon

### ISSUE THREAD

**Issue by StoIva** [rsimon/immarkus#31]
Hi.
high level folder still says 0 images, might be worth discussing if it should be a total of images in subfolders instead

**Comment by rsimon** [comment]
I have made a small change to this: the folder icon now shows number of (directly contained) images and (directly contained) subfolders. Let me know if this is sufficient. Otherwise, I'll have to implement a recursive count for the images. Not a huge deal, obviously, but takes a bit more time to implement.
