### ISSUE TITLE
geo coordinates issues

### ISSUE THREAD

**Issue by StoIva** [rsimon/immarkus#44]
The symbol for geo-coordinate is not shown in the properties editing view of the metadata 

1. Choose geo-coordinates datatype for location property in the folder metadata 
2. No geo-coordinates symbol next to location （compared to other properties shown with the symbols of properties）
3.  It also doesn’t add to the preview (no location and location 2 properties on the right side bar; I choose geo-coordinates for both properties) 
4. Both properties (location and location2) are added on the data model view so I think only preview is the problem 

![Screenshot (475)](https://github.com/rsimon/immarkus/assets/128056738/49473e55-9891-4a0c-888d-5332ca964662)
![Screenshot (473)](https://github.com/rsimon/immarkus/assets/128056738/75f07978-f94e-4476-8f47-16bdfbe29965)
![Screenshot 
![Screenshot (476)](https://github.com/rsimon/immarkus/assets/128056738/da0569a0-1860-4e10-baf2-c02128c6a58c)
(474)](https://github.com/rsimon/immarkus/assets/128056738/e2c716f9-5912-4f9d-a810-191569c4b868)

**Comment by StoIva** [comment]
![Screenshot (476)](https://github.com/rsimon/immarkus/assets/128056738/86dd0001-7c4c-4ae6-8849-ba62c8d2b584)

forgot 4 sorry

**Comment by rsimon** [comment]
Ouch - this is related to renaming "geo-coordinate" to "geo-coordinates". There was a piece of code I missed.

__This is now fixed!__ However, due to the bug, the fields you created above (without the icon) are now invalid. You'd need to delete them, and the re-create the coordinate-fields. (Refresh your browser first, to make sure you get the latest, bugfixed version from immarkus.rainersimon.io.)

P.S.: I also added another validation step internally, to prevent such a situation in the future.
