### ISSUE TITLE
more of a question: image google search function 

### ISSUE THREAD

**Issue by StoIva** [rsimon/immarkus#45]
I don’t want to ask if that is too much work; but is it possible if we add an image google search function as external authorities? Sometimes I want to look up some variant Chinese characters on the part of the image 

For instance, I want to look up the Chinese characters on the right side of this map; then would it be possible to tag this part and look up on the google image search? 
Maybe you already discussed this with Hilde; but would it be also possible to apply OCR function to such characters, so I don’t have to manually type them? 
![Screenshot (477)](https://github.com/rsimon/immarkus/assets/128056738/e59f005f-892f-4600-844c-b1189ef32a43)

**Comment by rsimon** [comment]
Hi @StoIva,

I just tried integrating Google Image search. It turns out this is not possible, unfortunately. Google has disallowed IFRAME embedding, which means their search page won't open when embedded into IMMARKUS.

I.e. the workaround is probably to open Google Image search in a separate tab, and then copy image URLs from there. That's much less integrated, of course. Let's keep thinking about it... perhaps there are alternative services that provide similar search services and are less restrictive?
