### ISSUE TITLE
entity classes grouped chronologically

### ISSUE THREAD

**Issue by StoIva** [rsimon/immarkus#54]
the classes are not grouping into child and parent in the data model view. they are grouping chronologically. see screenshot (circled in red)
![Screenshot (480)](https://github.com/rsimon/immarkus/assets/128056738/05460008-18b0-4b54-922e-beb1c290307f)

**Comment by rsimon** [comment]
I don't understand what you mean. Does `test parent` have itself a parent class? If it has no parent class defined, it has to be at the top level. Or am I misunderstanding your problem? 

Or do you mean that `test parent` is showing children that you have not actually assigned to it?

If, instead, you mean the sort order (rather than grouping): yes the list as such is sorted by order of creation. This means that the first (top-level!) parent you create is first in the (top-level!) list. If you open one of the top-level entity classes, then it's children will be sorted by order of creation, and so on.

In case this is what you mean: we could change sorting to alphabetically instead. (Display name rather than ID, presumably). Or would you want two "sections"? First only the entities with children (alphabetically), then entities without children (alphabetically)?

**Comment by StoIva** [comment]
test parent should be grouped with other parent classes, right? i thought we had this issue and that we group the classes by type (has childre or not), not in the order they were created?

**Comment by rsimon** [comment]
I don't think we discussed the sort order. The discussion was about collapsing rows that are actually children of other rows. (This is what I understand by "grouping". Each top-level entity becomes a collapsible node you can open and close.)

If you simply want the list sorted so that entities with children are first, I can add that easily.

**Comment by StoIva** [comment]
I think that would make them more user friendly? or do you have other suggestions?

**Comment by rsimon** [comment]
No, I think that would be fine. It would feel similar, in a way, to how file explorers present files, with folders first and files second. (And both, for example, sorted alphabetically.) Not the same thing, of course, but seems similar and sensible. I'll add that!

**Comment by rsimon** [comment]
This is now available on the [immarkus.rainersimon.io](https://immarkus.rainersimon.io) dev instance.
