### ISSUE TITLE
Editing parent properties in annotation view

### ISSUE THREAD

**Issue by StoIva** [rsimon/immarkus#62]
If I edit the property name in the annotation mode, it'll not be saved; in the data model it'll be successfully saved

**Comment by rsimon** [comment]
Hi @StoIva,

I think this is another issue related to inherited properties. I just made a small bugfix to the test server. What happened is this: 

- When you open an entity class in the editor, the preview (right side of the editor dialog) should __show__ all the properties, both the "native" ones, defined for this entity class, as well as the ones inherited from parents.
- But: only the "native" one should be editable.
- Because of a bug, the editor also mis-interpreted the parent properties as editable ones, when opened from in annotation mode.

This is now fixed. The entity class editor now behaves identically in annotation view and data model view.

I realize, however, it might be desirable to be able to edit parent properties in the annotation view, too. We should think about how to best do this from a UX perspective. Maybe something to discuss in the next meeting?

**Comment by rsimon** [comment]
__Update:__ when clicking the 'edit entity schema' button, you can now choose between editing the entity class of the tag, or any of it's ancestors in the hierarchy. (See screenshot below.) If the tag has no ancestors, clicking the button will directly open the class in the editor, as usual.

<img width="337" alt="Bildschirmfoto 2024-04-04 um 10 12 42" src="https://github.com/rsimon/immarkus/assets/470971/170289ae-89b3-446a-b0c6-b872d2e272ce">
