### ISSUE TITLE
bug: metadata properties

### ISSUE THREAD

**Issue by StoIva** [rsimon/immarkus#65]
whenever I save and reopen the folder metadata, the number property, geo coordinate and measurement are blank again, however they still appear in the json file

**Comment by rsimon** [comment]
Hi @StoIva, I cannot reproduce this. Here's what I tried:

- Created a folder schema with a geo-coordinate and a measurement property
- Opened 'Folder Information' of a folder, filled values for both fields.
- Clicked 'Save'
- Reopened the Folder Information -> fields still show the values I filled
- Reloaded the page, opened Folder Information -> fields still show the values I filled

I'll need more information in order to reproduce your problem. As much detail as you can provide - what are the field names, what are the values you provide, are there any error messages in the browser console?

Or alternatively: could you share i) the folder metadata file and ii) the data model file?

**Comment by StoIva** [comment]
no word of this reappearing. i will keep you updated

**Comment by StoIva** [comment]
issue persisting with second round of testing: whenever I save and reopen the folder metadata, the number property, geo coordinate and measurement are blank again, however they still appear in the json file
[IMMARKUS folder metadata error .docx](https://github.com/rsimon/immarkus/files/14744118/IMMARKUS.folder.metadata.error.docx)
[_immarkus.folder.meta.json](https://github.com/rsimon/immarkus/files/14744119/_immarkus.folder.meta.json)

**Comment by rsimon** [comment]
@StoIva, thanks I will try to reproduce. Can you also append the data model? (_immarkus.model.json, from the root folder?)

**Comment by StoIva** [comment]
i will ask for it now

**Comment by rsimon** [comment]
Hi @StoIva,

no worries - I tried a few things, and don't need the data model anymore. I can reproduce it now!

Interestingly, the error only happens if you have a __single__ folder schema defined in your data model. But not when you have more than one. That gives me enough to go on for debugging. Will report back soon.

**Comment by rsimon** [comment]
Hi @StoIva, 

happy to report that this should now be fixed!
