### ISSUE TITLE
export- annotations

### ISSUE THREAD

**Issue by StoIva** [rsimon/immarkus#87]
not all the annotations are exported in the xls, only 3/10

**Comment by rsimon** [comment]
Thanks for reporting! I think I can see what's going on. Only three of the annotations have properties, the others seem to be empty. That's probably what causes the problem. I'll investigate!

**Comment by rsimon** [comment]
Sorry - I looked at this again, and it turns out there's actually no bug in IMMARKUS.

- The `annotation.json` file contains 12 annotations
  - 2 of those contain image metadata, which is not currently exported to Excel
  - 1 annotation was not tagged as an entity

The remaining 9 annotations are all in the Excel that you posted. Keep in mind that the export will create a __separate worksheet for each top-level entity class__. It's easy to miss if you open the file in Excel. But the worksheets will be listed at the bottom of the screen in Excel.
